name: Update PR Template

on:
  workflow_dispatch:
    inputs:
      template_file:
        description: "Which PR template do you want to use?"
        required: true
        type: choice
        options:
          - mfe_template.md
          - plugin_template.md
          - tutor_pearson_plugin_template.md
        default: "plugin_template.md"
      target_repo:
        description: "Name of the target repository to update"
        required: true
        default: "catalog-plugin"

jobs:
  update-template:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: Pearson-Advance
      TARGET_REPO: ${{ github.event.inputs.target_repo }}
      # NOTE: Implement the correct Github token usage.
      GH_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
    steps:
      - name: Check out this repository (contains the .md files)
        uses: actions/checkout@v3

      - name: List repository files for debugging (optional)
        run: |
          pwd
          ls -R

      - name: Load chosen template file
        id: load_template
        run: |
          echo "template<<EOF" >> $GITHUB_OUTPUT
          # The template file name is chosen at runtime via the `template_file` input
          cat ${{ github.event.inputs.template_file }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install GitHub CLI (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone target repository
        run: |
          gh repo clone $ORG_NAME/$TARGET_REPO target-repo

      - name: Configure Git and update remote URL
        run: |
          cd target-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$ORG_NAME/$TARGET_REPO.git

      - name: Create branch and update PR template
        run: |
          cd target-repo
          if git show-ref --verify --quiet refs/heads/update-pr-template; then
            git checkout update-pr-template
          else
            git checkout -b update-pr-template
          fi
          mkdir -p .github
          echo "${{ steps.load_template.outputs.template }}" > .github/PULL_REQUEST_TEMPLATE.md
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "docs: update PR template." || echo "No changes to commit"
          git push origin update-pr-template --force

      - name: Create Pull Request
        run: |
          cd target-repo
          gh pr create \
            --title "docs: update PR Template." \
            --body "This PR updates the pull request template for consistency." \
            || echo "PR already exists or cannot be created"
