name: Update PR Template

on:
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: Pearson-Advance
      TARGET_REPO: catalog-plugin    # NOTE: Temporary target repo
      GH_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
      PR_TEMPLATE_CONTENT: |
        ## Tickets

        - [JIRA Ticket](URL)  
          *Contains the link to the related task or ticket for this Pull Request from the task management system (e.g., JIRA) to facilitate tracking.*

        ## Description

        *Briefly describe the purpose of this Pull Request. Provide context about the changes made, explaining the reasons and objectives.*

        **Example:**  
        This PR adds the `BaseDatatableView` Django library to ingest a datatable for displaying the lab detail list.

        ## Changes Made

        *List the changes you have made in the code. Use a checklist to highlight the most important parts of the code and functionalities added or modified.*

        **Example:**
        - [x] Created a class `BaseDatatableView` in `datatables.py` to handle the ingestion of the lab detail list.
        - [x] Added a new URL in `urls.py` for the `BaseDatatableView`.
        - [x] Developed the `datatables.js` script to launch the new datatable in a modal when clicking an instance in the student roster datatable, handling data ingestion via AJAX.

        ## How to Test

        *Provide clear, step-by-step instructions on how to test your changes. Include detailed steps so that reviewers or testers can replicate the functionality and verify the expected results.*

        **Example:**
        1. Navigate to the **Instructor's tab** from a user account with an active lab.
        2. Verify that the table correctly displays the lab detail list.
        3. Test the **search bar** functionality to ensure it filters the table data as expected.
        4. Confirm that clicking on any student in the roster opens a modal with the correct lab details.

        ## Screenshots (optional)

        *If applicable, include screenshots to visually demonstrate the changes you’ve made, especially if they affect the UI or include animated .GIFs showing how to test the functionality.*

        **Example:**  
        ![Example Screenshot](https://example.com/screenshot.png)

        ## Dependencies (optional)

        *List any dependencies this Pull Request relies on (e.g., libraries, packages, or other PRs). Indicate if any dependencies need to be added to configuration files like `requirements.txt`.*

        **Example:**
        - Ensure the `BaseDatatableView` library is included in the requirements file or installed correctly.

        ## Additional Context (optional)

        *Include any extra information that might be helpful for reviewers or testers (e.g., details about the test environment, known issues, or limitations).*

        **Example:**  
        Any additional notes or context that may help reviewers or testers.
    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone target repository
        run: |
          gh repo clone $ORG_NAME/$TARGET_REPO target-repo

      - name: Configure Git and update remote URL
        run: |
          cd target-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$ORG_NAME/$TARGET_REPO.git

      - name: Create branch and update PR template
        run: |
          cd target-repo
          if git show-ref --verify --quiet refs/heads/update-pr-template; then
            git checkout update-pr-template
          else
            git checkout -b update-pr-template
          fi
          mkdir -p .github
          echo "$PR_TEMPLATE_CONTENT" > .github/PULL_REQUEST_TEMPLATE.md
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Update PR template" || echo "No changes to commit"
          git push origin update-pr-template --force

      - name: Create Pull Request
        run: |
          cd target-repo
          gh pr create --title "Update PR Template" --body "This PR updates the pull request template for consistency." || echo "PR already exists or cannot be created"
  