name: Update PR Template

on:
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: Pearson-Advance
      TARGET_REPO: catalog-plugin # NOTE: Implement a generalization for all repos.
      GH_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}  # NOTE: Implement the correct Github token usage.
    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v3

      # NOTE: Generalize for all md chosing which repos we want to update.
      - name: Load PR template from file
        id: load_template
        run: |
          # Read the content of the PR template file and set it as an output variable
          echo "template<<EOF" >> $GITHUB_OUTPUT
          cat plugin_template.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install GitHub CLI (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone target repository
        run: |
          gh repo clone $ORG_NAME/$TARGET_REPO target-repo

      - name: Configure Git and update remote URL
        run: |
          cd target-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/$ORG_NAME/$TARGET_REPO.git

      - name: Create branch and update PR template
        run: |
          cd target-repo
          if git show-ref --verify --quiet refs/heads/update-pr-template; then
            git checkout update-pr-template
          else
            git checkout -b update-pr-template
          fi
          mkdir -p .github
          # Use the output variable from the 'load_template' step
          echo "${{ steps.load_template.outputs.template }}" > .github/PULL_REQUEST_TEMPLATE.md
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Update PR template" || echo "No changes to commit"
          git push origin update-pr-template --force

      # NOTE: Update the PR description properly.
      - name: Create Pull Request
        run: |
          cd target-repo
          gh pr create --title "docs: update PR Template." --body "This PR updates the pull request template for consistency." || echo "PR already exists or cannot be created"
